### ISSUE TITLE
comparision of resultant images with different batchsizes 

### ISSUE THREAD

**Issue by Syeda-Farhat** [zyxu1996/Efficient-Transformer#1]
The resultant image changes with different batchsizes, why?
<img width="302" alt="problem" src="https://user-images.githubusercontent.com/80599648/169024279-07389e7f-9f5c-40e2-b82f-d320d8e2416c.PNG">
)

**Comment by zyxu1996** [comment]
How did you run the test code command? The result should not be related to the batch size. Maybe you should run the test code in the corresponding work_dir.

**Comment by zyxu1996** [comment]
It seems the network params are random initialized.

**Comment by zyxu1996** [comment]
The val batchsizes are used to accelerate the inferring process.

**Comment by Syeda-Farhat** [comment]
I just checked with different batch sizes and in the same corresponding work_dir. yes you are right results should not be affected but unfortunately :( 
> 
<img width="960" alt="p1" src="https://user-images.githubusercontent.com/80599648/169142912-123cf607-64cc-4888-bfa1-9c0912d732c3.PNG">

**Comment by zyxu1996** [comment]
I noticed that your trained weights are saved in tmp_save dir, but the information in the test command is num1. Both the names should be same, otherwise the model can not read the right trained weights.

**Comment by zyxu1996** [comment]
Have you trained the model? If you don't train the model, you will not get the trained weights in the work_dir, so the loaded trained weight are randomly initialized.

**Comment by zyxu1996** [comment]
Different loaded weight will output different results.

**Comment by Syeda-Farhat** [comment]
oh yes, now I get the point. I will try again with these changes. Thank You so much for your response.
