### ISSUE TITLE
您好，请问您在论文中的miou是前五类还是包含了背景6个类

### ISSUE THREAD

**Issue by stdcoutzrh** [zyxu1996/Efficient-Transformer#5]

**Comment by zyxu1996** [comment]
不包含背景类

**Comment by stdcoutzrh** [comment]
您好，感谢您这么快回复。我看您的论文中vaihingen的结果在76左右。我在跑其他模型的代码的时候也在76，77左右，怎么都跑不到一些论文中82左右的miou。比如这里的一些模型 https://github.com/WangLibo1995/GeoSeg 请问您遇到过这种情况嘛。

**Comment by zyxu1996** [comment]
正常情况下，模型间的miou差距应该没那么大。考虑下面两点云因：1、可能是数据划分方式不同 2、可能是miou计算方式不同，比如有些方式是统计所有pixel计算miou，有些是统计每个patch的iou计算得到miou。建议你在https://github.com/WangLibo1995/GeoSeg 这个框架下跑跑infer试试

**Comment by stdcoutzrh** [comment]
好的 感谢您的回复 祝您新年快乐，工作学习顺利
